---

- hosts: db
  become: true
  tasks:
  
  - name: update repo
    apt:
      update_cache: yes
 
  - name: install apache2 && UFW && WGET
    apt: 
      name:
        - apache2
        - mariadb-server
        - mariadb-client
        - libapache2-mod-php
        - pip
      state: latest
      update_cache: yes

  - name: start apache2  
    service:
      name: apache2
      state: started
      enabled: yes
  
  - name: install python 
    pip:
      name: pymysql
  
  - name: start mariadb
    service: 
      name: mariadb
      enabled: yes
      state: started
  
  - name: Create my database
    mysql_db:
      name: myserverdb
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock


  - name: Create users and grant priv
    mysql_user:
      name: pelumi
      password: General1
      priv: 'myserverdb.*:ALL'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true
      
  - name: apt update
    tags: update
    apt:
      update_cache: yes

