---

- hosts: db
  become: true
  tasks:
  
  - name: update repo
    apt:
      update_cache: yes
 
  - name: install apache2 && UFW && WGET
    tags: php
    apt: 
      name:
        - apache2
        - mariadb-server
        - php
        - php-curl
        - php-xml
        - php8.1-zip
        - php8.1-dev
        - php-mbstring
        - php-mysql
        - php8.1-gd
        - php8.1-cli
        - php8.1-common
        - curl
        - mariadb-client
        - libapache2-mod-php
        - pip
      state: latest
      update_cache: yes

  - name: start apache2  
    service:
      name: apache2
      state: started
      enabled: yes
  
  - name: install python 
    pip:
      name: pymysql
  
  - name: start mariadb
    service: 
      name: mariadb
      enabled: yes
      state: started
  
  - name: Create my database
    mysql_db:
      name: myserverdb
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock


  - name: Create users and grant priv
    mysql_user:
      name: pelumi
      password: General1
      priv: 'myserverdb.*:ALL'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true
      
  - name: apt update
    tags: update
    apt:
      update_cache: yes

  - name: change upload_max_filesize
    tags: file_change
    lineinfile:
      path: /etc/php/8.1/apache2/php.ini
      regexp: '^upload_max_filesize'
      line: upload_max_filesize = 32M

  - name: change post_max_size
    tags: file_change
    lineinfile:
      path: /etc/php/8.1/apache2/php.ini
      regexp: 'post_max_size'
      line: post_max_size = 48M
    register: php_ini

  - name: change memory_limit
    tags: file_change
    lineinfile:
      path: /etc/php/8.1/apache2/php.ini
      regexp: 'memory_limit'
      line: memory_limit = 256M
    register: php_ini

  - name: change max_execution
    tags: file_change
    lineinfile:
      path: /etc/php/8.1/apache2/php.ini
      regexp: 'max_execution_time'
      line: max_execution_time = 600
    register: php_ini

  - name: change max_input_vars
    tags: file_change
    lineinfile: 
      path: /etc/php/8.1/apache2/php.ini
      regexp: 'max_input_vars'
      line: max_input_vars = 3000 
    register: php_ini

  - name: change max_input_time
    tags: file_change
    lineinfile:
      path: /etc/php/8.1/apache2/php.ini
      regexp: 'max_input_time'
      line: max_input_time = 1000
    register: php_ini


  - name: restart apche2
    tags: file_change    
    service:
      name: apache2
      state: restarted
    when: php_ini.changed


  - name: disable apache configuration
    tags: apache2
    shell:
      cmd: a2dissite 000-default

  - name: enable rewrite
    shell:
      cmd: a2enmod rewrite
  
  - name: check if laravel clone exists
    stat:
      path: /var/www/laravel-realword-example-app
    register: laravel


  - name: clone laravel repo
    tags: laravel
    git:
      repo: https://github.com/oxblixxx/laravel-realworld-example-app.git
      dest: /var/www/laravel-realworld-example-app
      clone: yes
      update: no
    when: laravel.stat.exists == false

  - name: check if .env.example exists
    stat:
      path: /var/www/laravel-realworld-example-app/.env.example
    register: env_exist

  - name: check if web.php exists
    stat:
      path: /var/www/laravel-realworld-example-app/routes/web.php
    register: web_php

  - name: remove .env .example
    tags: change_en
    file:
      path: /var/www/laravel-realworld-example-app/.env.example
      state: absent
    when: env_exist.stat.exists == true

  - name: remove web.php
    tags: changr
    file:
      path: /var/www/laravel-realworld-example-app/routes/web.php
      state: absent
      when: web_php.stat.exists == true

  - name: copy .env file to server
    tags: copy_file
    copy:
      src: .env
      dest: /var/www/laravel-realworld-example-app/
      remote_src: false

  - name: copy web.php to server
    tags: copy_file
    copy: 
      src: web.php
      dest: /var/www/laravel-realworld-example-app/routes/
      remote_src: false


  - name: copy .htaccess to server
    tags: copy_file
    copy:
      src: .htaccess
      dest: /var/www/laravel-realworld-example-app/
      remote_src: false

  - name: download composer
    tags: composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer

  - name: run composer installer
    tags: composer
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
    args:
      creates: /usr/local/bin/composer
 
  - name: move compose.phar
    tags: composer
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    args:
        creates: /usr/local/bin/composer

  - name: make composer executable
    file:
      path: /usr/local/bin/composer
      mode: a+x
      state: file

  - name: composer update
    tags: composer_o
    shell:
      cmd: composer update --no-interaction
      chdir: /var/www/laravel-realworld-example-app/

  - name: composer install
    tags: composer_o
    shell:
      cmd: composer install --no-interaction
      chdir: /var/www/laravel-realworld-example-app/

  - name: key generate
    tags: artisan
    shell:
      cmd: php artisan key:generate
      chdir: /var/www/laravel-realworld-example-app/
 
  - name: php artisan migrate seed
    tags: artisan
    shell:
      cmd: php artisan config:cache
      chdir: /var/www/laravel-realworld-example-app/

  - name: php artisan
    tags: artisan_r
    shell:
      cmd: php artisan migrate:refresh
      chdir: /var/www/laravel-realworld-example-app/
 
  - name: php artisan migrate seed
    tags: artisan_r
    shell:
      cmd: php artisan migrate:refresh --seed
      chdir: /var/www/laravel-realworld-example-app/

  - name: change file permissions
    tags: file_permission
    file:
      path: /var/www/laravel-realworld-example-app/
      owner: www-data
      group: www-data
      mode: 0775
      modification_time: now      
      recurse: yes

  - name: copy conf file
    tags: conf
    copy:
      src: laravel-realworld-example-app.conf
      dest: /etc/apache2/sites-available
      remote_src: false

  
  - name: enable laravel configuration
    tags: apache2
    shell:
      cmd: a2ensite laravel-realworld-example-app.conf

  - name: restart apache
    tags: apache2
    shell:
      cmd: systemctl restart apache2 
