---

- hosts: db
  become: true
  tasks:
  
  - name: update repo
    apt:
      update_cache: yes
 
  - name: install apache2 && UFW && WGET
    apt: 
      name:
        - apache2
        - wget
        - ufw
        - software-properties-common
        - mariadb-server
        - mariadb-client
        - python3-pip
        - lsb-release
        - apt-transport-https
        - ca-certificates
      state: latest
      update_cache: yes	

  - name: start apache2  
    service:
      name: apache2
      state: started
      enabled: yes

  - name: enable ufw
    ufw:
      state: enabled
  
  - name: allow ssh
    ufw:
      rule: allow
      name: SSH

  - name: allow WWW
    ufw:
      rule: allow
      name: WWW FULL

  - name: allow openssh
    ufw:
      rule: allow
      name: OpenSSH

  - name: start mariadb
    service: 
      name: mariadb
      enabled: yes
      state: started

  - name: Install PyMySQL
    pip: 
      name: pymysql
      state: latest
      
  - name: key
    tags: key
    shell:
      cmd: 
          
      warn: False    
 
  - name: add ppa packages
    tags: add
    command: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list

  - name: apt update
    tags: update
    apt:
      update_cache: yes
      upgrade: dist
  
  - name: install php
    tags: install_php
    apt:
      name: 
        - php 
        - libapache2-mod-php 
      state: latest
