#!/bin/bash

echo " ____________________________________"
echo "|                                   |" 
echo "|"preparing your installation files"|"
echo "|___________________________________|"
sleep 5
echo "--"
sleep 4
echo "---"
sleep 3
echo "----"
sleep 2
echo "-----"

echo "=========================="
echo "running your distro upgrade"
echo "=========================="

sleep 3

# Distro upgrade
update() {
  sudo apt update -y
  sudo apt upgrade -y
}

# () for distro upgrade
update


echo "==============="
echo "update complete"
echo "==============="

# Install Curl and check if it's pre-installed
if version=$(dpkg-query -W -f='${Version}' curl >/dev/null); then 

    # Check if it's older than 7.74
    if dpkg --compare-versions "$version" '<' 7.74; then
        echo "curl not in latest version"
        apt remove curl -y || exit
    else
        echo 'Attention! you have curl installed'
        exit
    fi
sleep 5
fi

sleep 6

sudo apt-get update -y &&
sudo apt install -y curl apt-transport-https

sleep 4

echo "================================="
echo "success curl succesfully installed"
echo "================================="

sleep 4

# Import PostgreSQL signing key
echo "==========================================="
echo " preparing to import PostgreSQL signing key"
echo "==========================================="

sleep 4

curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/postgresql-keyring.gpg

sleep 3

echo "==============================="
echo "signing key sucesfully imported"
echo "==============================="

sleep 2

# Add the postgreSQL repo to you distro

echo "===================================="
echo "adding PostgreSQL info to the distro"
echo "===================================="

sleep 2

echo "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql.list
echo "======================"
echo "info added succesfully"
echo "======================"

sleep 4

echo "========================="
echo " running update, Hold on!"
echo "========================="

# Run update 

# () for distro ugrade
update


sleep 3

echo "==============="
echo "updated success"
echo "==============="

sleep 1

# Install PostgreSQL

echo "====================="
echo "Installing PostgreSQL"
echo "====================="

sleep 2

# Check if PostgreSQL version is 13 otherwise install
if version=$(dpkg-query -W -f='${Version}' postgresql >/dev/null); then

   # Check if it's older than 13
    if dpkg --compare-versions "$version" '<' 13; then
        echo "postgresql not in latest version"
        apt remove postgresql -y || exit
    else
        echo 'Attention! you have curl installed'
        exit
    fi
sleep 5
fi

sudo apt install postgresql -y

sleep 3

echo "======="
echo "success"
echo "======="


# Run update and Upgrade

update

echo "=============="
echo "update success"
echo "=============="


# Enable and start postgresql
sleep 2
sudo systemctl enable postgresql

echo "=================="
echo "Postgresql enabled"
echo "=================="

sleep 2

sudo systemctl start postgresql

echo "==================="
echo "Postgresql started"
echo "==================="


# Create conf for postgress

sed -i "58 s/^/listen_addresses = '*'            #What address(es) to listen to "  /etc/postgresql/15/main/postgres.sql
